services:
  db:
    image: postgres:16-alpine
    container_name: gestion_affectations_db
    environment:
      POSTGRES_DB: gestion_affectations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # TODO : Should put these configurations into one .env file
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d postgres']
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - '8081:8080'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
